server:
    port: 8081
spring:
    application:
        name: music
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/music?serverTimezone=UTC
        username: root
        password: 199934lt
    profiles:
        active: dev
    devtools:
        restart:
            enabled: true
            additional-paths: src/main
    thymeleaf:
        prefix: classpath:/templates/
        encoding: UTF-8
        excluded-view-names: ''
        suffix: .html
        mode: HTML
        content-type: text/html;charset=utf-8
        cache: false
    mvc:
        format:
            date-time: yyyy-MM-dd HH:mm:ss
    web:
        resources:
            static-locations: classpath:/static

mybatis:
    type-aliases-package: net.ltbk.music.mapper
    mapper-locations: classpath:mapper/*xml
    config-location: classpath:mybatis-config.xml
logging:
    config: classpath:logback.xml
    file:
        path: /log